### ISSUE TITLE
Upgrading to Apollo Client 2.0

### ISSUE THREAD

**Issue by drejohnson** [Gregoirevda/reason-apollo#1]
I tried updating repo to use Apollo Client 2.0 and now I'm getting this type error:

```
42 ┆ (response) => {
  43 ┆   Js.log(response);
  44 ┆   let title = response##loading ? "" : response##data##episode##title;
  45 ┆   <div> (text(title)) </div>
  46 ┆ }
  
  This is:
    Config.responseType
  But somewhere wanted:
    Js.t('a)
```

Any insight on what I'm doing wrong?

My reason-apollo fork
[https://github.com/drejohnson/reason-apollo](https://github.com/drejohnson/reason-apollo)

My test repo
[https://github.com/drejohnson/with-reason-apollo](https://github.com/drejohnson/with-reason-apollo)

**Comment by drejohnson** [comment]
Seems like it might have something to do with my query. Using your reason-apollo-test-usage repo works with the update to Apollo Client 2.0.

**Comment by Gregoirevda** [comment]
This looks awesome. I made a PR in your with-reason-apollo repo. You simply missed some quotes on the Js types.
Thanks for the reason upgrade to v3 and usage with Apollo Client 2!

**Comment by drejohnson** [comment]
Thanks. I sent a PR.
