### ISSUE TITLE
Passing Variables?

### ISSUE THREAD

**Issue by idkjs** [Gregoirevda/reason-apollo#4]
Any idea on how to pass variables? Example, we render a list then onClick we want to open a single item page view which passes the item ID as a variable to getUser for a specific user?

**Comment by Gregoirevda** [comment]
The repo showing the usage has been updated as well as the package. You can know pass variables to your queries like that: 
```
let variables = {
  "limit": 2
};

module FetchTodos = Apollo.Client({
  type responseType = data;
  type variables = {. "limit": int};
});

<FetchTodos query variables>
  ((response) => {
    switch response##loading {
       | true => <div> (Utils.ste("Loading")) </div>
       | false => <div> (Utils.ste(response##data))</div>
       }
    };
  })
</FetchTodos>
```

If you don't want to pass variables, you still need to define the variable type like so:
```
module FetchTodos = Apollo.Client({
  type responseType = data;
  type variables;
});
```
