### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by fakenickels** [Gregoirevda/reason-apollo#9]
I think a simple "bsb -make-world" would be enough for a CI now, just to check if the code compiles ✅ 

It's how I'm doing in my company projects

https://github.com/Astrocoders/reform/blob/master/package.json#L19
I have this setup for travis

**Comment by Gregoirevda** [comment]
Good idea, I'll compare Travis and CircleCI!

**Comment by fakenickels** [comment]
Solved by https://github.com/Gregoirevda/reason-apollo/pull/10
